//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forex.FortuneMoney_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://yakose.dk/", ConfigurationName="FortuneMoney_ServiceReference.FortuneMoneySrv")]
    public interface FortuneMoneySrv {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://yakose.dk/)
        [System.ServiceModel.OperationContractAttribute(Action="http://yakose.dk/FortuneMoneySrv/exchangeFromKroneToDollarRequest", ReplyAction="http://yakose.dk/FortuneMoneySrv/exchangeFromKroneToDollarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarResponse exchangeFromKroneToDollar(Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yakose.dk/FortuneMoneySrv/exchangeFromKroneToDollarRequest", ReplyAction="http://yakose.dk/FortuneMoneySrv/exchangeFromKroneToDollarResponse")]
        System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarResponse> exchangeFromKroneToDollarAsync(Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://yakose.dk/)
        [System.ServiceModel.OperationContractAttribute(Action="http://yakose.dk/FortuneMoneySrv/exchangeFromDollarToKroneRequest", ReplyAction="http://yakose.dk/FortuneMoneySrv/exchangeFromDollarToKroneResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneResponse exchangeFromDollarToKrone(Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yakose.dk/FortuneMoneySrv/exchangeFromDollarToKroneRequest", ReplyAction="http://yakose.dk/FortuneMoneySrv/exchangeFromDollarToKroneResponse")]
        System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneResponse> exchangeFromDollarToKroneAsync(Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://yakose.dk/)
        [System.ServiceModel.OperationContractAttribute(Action="http://yakose.dk/FortuneMoneySrv/exchangeFromKroneToPoudRequest", ReplyAction="http://yakose.dk/FortuneMoneySrv/exchangeFromKroneToPoudResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudResponse exchangeFromKroneToPoud(Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yakose.dk/FortuneMoneySrv/exchangeFromKroneToPoudRequest", ReplyAction="http://yakose.dk/FortuneMoneySrv/exchangeFromKroneToPoudResponse")]
        System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudResponse> exchangeFromKroneToPoudAsync(Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://yakose.dk/)
        [System.ServiceModel.OperationContractAttribute(Action="http://yakose.dk/FortuneMoneySrv/exchangeFromPoundToKroneRequest", ReplyAction="http://yakose.dk/FortuneMoneySrv/exchangeFromPoundToKroneResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneResponse exchangeFromPoundToKrone(Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yakose.dk/FortuneMoneySrv/exchangeFromPoundToKroneRequest", ReplyAction="http://yakose.dk/FortuneMoneySrv/exchangeFromPoundToKroneResponse")]
        System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneResponse> exchangeFromPoundToKroneAsync(Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://yakose.dk/)
        [System.ServiceModel.OperationContractAttribute(Action="http://yakose.dk/FortuneMoneySrv/exchangeFromEuroToKroneRequest", ReplyAction="http://yakose.dk/FortuneMoneySrv/exchangeFromEuroToKroneResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneResponse exchangeFromEuroToKrone(Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yakose.dk/FortuneMoneySrv/exchangeFromEuroToKroneRequest", ReplyAction="http://yakose.dk/FortuneMoneySrv/exchangeFromEuroToKroneResponse")]
        System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneResponse> exchangeFromEuroToKroneAsync(Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://yakose.dk/)
        [System.ServiceModel.OperationContractAttribute(Action="http://yakose.dk/FortuneMoneySrv/exchangeFromKroneToEuroRequest", ReplyAction="http://yakose.dk/FortuneMoneySrv/exchangeFromKroneToEuroResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroResponse exchangeFromKroneToEuro(Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yakose.dk/FortuneMoneySrv/exchangeFromKroneToEuroRequest", ReplyAction="http://yakose.dk/FortuneMoneySrv/exchangeFromKroneToEuroResponse")]
        System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroResponse> exchangeFromKroneToEuroAsync(Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exchangeFromKroneToDollar", WrapperNamespace="http://yakose.dk/", IsWrapped=true)]
    public partial class exchangeFromKroneToDollarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double fromAmount;
        
        public exchangeFromKroneToDollarRequest() {
        }
        
        public exchangeFromKroneToDollarRequest(double fromAmount) {
            this.fromAmount = fromAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exchangeFromKroneToDollarResponse", WrapperNamespace="http://yakose.dk/", IsWrapped=true)]
    public partial class exchangeFromKroneToDollarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public exchangeFromKroneToDollarResponse() {
        }
        
        public exchangeFromKroneToDollarResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exchangeFromDollarToKrone", WrapperNamespace="http://yakose.dk/", IsWrapped=true)]
    public partial class exchangeFromDollarToKroneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double fromAmount;
        
        public exchangeFromDollarToKroneRequest() {
        }
        
        public exchangeFromDollarToKroneRequest(double fromAmount) {
            this.fromAmount = fromAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exchangeFromDollarToKroneResponse", WrapperNamespace="http://yakose.dk/", IsWrapped=true)]
    public partial class exchangeFromDollarToKroneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public exchangeFromDollarToKroneResponse() {
        }
        
        public exchangeFromDollarToKroneResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exchangeFromKroneToPoud", WrapperNamespace="http://yakose.dk/", IsWrapped=true)]
    public partial class exchangeFromKroneToPoudRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double fromAmount;
        
        public exchangeFromKroneToPoudRequest() {
        }
        
        public exchangeFromKroneToPoudRequest(double fromAmount) {
            this.fromAmount = fromAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exchangeFromKroneToPoudResponse", WrapperNamespace="http://yakose.dk/", IsWrapped=true)]
    public partial class exchangeFromKroneToPoudResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public exchangeFromKroneToPoudResponse() {
        }
        
        public exchangeFromKroneToPoudResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exchangeFromPoundToKrone", WrapperNamespace="http://yakose.dk/", IsWrapped=true)]
    public partial class exchangeFromPoundToKroneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double fromAmount;
        
        public exchangeFromPoundToKroneRequest() {
        }
        
        public exchangeFromPoundToKroneRequest(double fromAmount) {
            this.fromAmount = fromAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exchangeFromPoundToKroneResponse", WrapperNamespace="http://yakose.dk/", IsWrapped=true)]
    public partial class exchangeFromPoundToKroneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public exchangeFromPoundToKroneResponse() {
        }
        
        public exchangeFromPoundToKroneResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exchangeFromEuroToKrone", WrapperNamespace="http://yakose.dk/", IsWrapped=true)]
    public partial class exchangeFromEuroToKroneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double fromAmount;
        
        public exchangeFromEuroToKroneRequest() {
        }
        
        public exchangeFromEuroToKroneRequest(double fromAmount) {
            this.fromAmount = fromAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exchangeFromEuroToKroneResponse", WrapperNamespace="http://yakose.dk/", IsWrapped=true)]
    public partial class exchangeFromEuroToKroneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public exchangeFromEuroToKroneResponse() {
        }
        
        public exchangeFromEuroToKroneResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exchangeFromKroneToEuro", WrapperNamespace="http://yakose.dk/", IsWrapped=true)]
    public partial class exchangeFromKroneToEuroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double fromAmount;
        
        public exchangeFromKroneToEuroRequest() {
        }
        
        public exchangeFromKroneToEuroRequest(double fromAmount) {
            this.fromAmount = fromAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exchangeFromKroneToEuroResponse", WrapperNamespace="http://yakose.dk/", IsWrapped=true)]
    public partial class exchangeFromKroneToEuroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public exchangeFromKroneToEuroResponse() {
        }
        
        public exchangeFromKroneToEuroResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FortuneMoneySrvChannel : Forex.FortuneMoney_ServiceReference.FortuneMoneySrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FortuneMoneySrvClient : System.ServiceModel.ClientBase<Forex.FortuneMoney_ServiceReference.FortuneMoneySrv>, Forex.FortuneMoney_ServiceReference.FortuneMoneySrv {
        
        public FortuneMoneySrvClient() {
        }
        
        public FortuneMoneySrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FortuneMoneySrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FortuneMoneySrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FortuneMoneySrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarResponse Forex.FortuneMoney_ServiceReference.FortuneMoneySrv.exchangeFromKroneToDollar(Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarRequest request) {
            return base.Channel.exchangeFromKroneToDollar(request);
        }
        
        public double exchangeFromKroneToDollar(double fromAmount) {
            Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarRequest inValue = new Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarRequest();
            inValue.fromAmount = fromAmount;
            Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarResponse retVal = ((Forex.FortuneMoney_ServiceReference.FortuneMoneySrv)(this)).exchangeFromKroneToDollar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarResponse> Forex.FortuneMoney_ServiceReference.FortuneMoneySrv.exchangeFromKroneToDollarAsync(Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarRequest request) {
            return base.Channel.exchangeFromKroneToDollarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarResponse> exchangeFromKroneToDollarAsync(double fromAmount) {
            Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarRequest inValue = new Forex.FortuneMoney_ServiceReference.exchangeFromKroneToDollarRequest();
            inValue.fromAmount = fromAmount;
            return ((Forex.FortuneMoney_ServiceReference.FortuneMoneySrv)(this)).exchangeFromKroneToDollarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneResponse Forex.FortuneMoney_ServiceReference.FortuneMoneySrv.exchangeFromDollarToKrone(Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneRequest request) {
            return base.Channel.exchangeFromDollarToKrone(request);
        }
        
        public double exchangeFromDollarToKrone(double fromAmount) {
            Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneRequest inValue = new Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneRequest();
            inValue.fromAmount = fromAmount;
            Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneResponse retVal = ((Forex.FortuneMoney_ServiceReference.FortuneMoneySrv)(this)).exchangeFromDollarToKrone(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneResponse> Forex.FortuneMoney_ServiceReference.FortuneMoneySrv.exchangeFromDollarToKroneAsync(Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneRequest request) {
            return base.Channel.exchangeFromDollarToKroneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneResponse> exchangeFromDollarToKroneAsync(double fromAmount) {
            Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneRequest inValue = new Forex.FortuneMoney_ServiceReference.exchangeFromDollarToKroneRequest();
            inValue.fromAmount = fromAmount;
            return ((Forex.FortuneMoney_ServiceReference.FortuneMoneySrv)(this)).exchangeFromDollarToKroneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudResponse Forex.FortuneMoney_ServiceReference.FortuneMoneySrv.exchangeFromKroneToPoud(Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudRequest request) {
            return base.Channel.exchangeFromKroneToPoud(request);
        }
        
        public double exchangeFromKroneToPoud(double fromAmount) {
            Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudRequest inValue = new Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudRequest();
            inValue.fromAmount = fromAmount;
            Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudResponse retVal = ((Forex.FortuneMoney_ServiceReference.FortuneMoneySrv)(this)).exchangeFromKroneToPoud(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudResponse> Forex.FortuneMoney_ServiceReference.FortuneMoneySrv.exchangeFromKroneToPoudAsync(Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudRequest request) {
            return base.Channel.exchangeFromKroneToPoudAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudResponse> exchangeFromKroneToPoudAsync(double fromAmount) {
            Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudRequest inValue = new Forex.FortuneMoney_ServiceReference.exchangeFromKroneToPoudRequest();
            inValue.fromAmount = fromAmount;
            return ((Forex.FortuneMoney_ServiceReference.FortuneMoneySrv)(this)).exchangeFromKroneToPoudAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneResponse Forex.FortuneMoney_ServiceReference.FortuneMoneySrv.exchangeFromPoundToKrone(Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneRequest request) {
            return base.Channel.exchangeFromPoundToKrone(request);
        }
        
        public double exchangeFromPoundToKrone(double fromAmount) {
            Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneRequest inValue = new Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneRequest();
            inValue.fromAmount = fromAmount;
            Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneResponse retVal = ((Forex.FortuneMoney_ServiceReference.FortuneMoneySrv)(this)).exchangeFromPoundToKrone(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneResponse> Forex.FortuneMoney_ServiceReference.FortuneMoneySrv.exchangeFromPoundToKroneAsync(Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneRequest request) {
            return base.Channel.exchangeFromPoundToKroneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneResponse> exchangeFromPoundToKroneAsync(double fromAmount) {
            Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneRequest inValue = new Forex.FortuneMoney_ServiceReference.exchangeFromPoundToKroneRequest();
            inValue.fromAmount = fromAmount;
            return ((Forex.FortuneMoney_ServiceReference.FortuneMoneySrv)(this)).exchangeFromPoundToKroneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneResponse Forex.FortuneMoney_ServiceReference.FortuneMoneySrv.exchangeFromEuroToKrone(Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneRequest request) {
            return base.Channel.exchangeFromEuroToKrone(request);
        }
        
        public double exchangeFromEuroToKrone(double fromAmount) {
            Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneRequest inValue = new Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneRequest();
            inValue.fromAmount = fromAmount;
            Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneResponse retVal = ((Forex.FortuneMoney_ServiceReference.FortuneMoneySrv)(this)).exchangeFromEuroToKrone(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneResponse> Forex.FortuneMoney_ServiceReference.FortuneMoneySrv.exchangeFromEuroToKroneAsync(Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneRequest request) {
            return base.Channel.exchangeFromEuroToKroneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneResponse> exchangeFromEuroToKroneAsync(double fromAmount) {
            Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneRequest inValue = new Forex.FortuneMoney_ServiceReference.exchangeFromEuroToKroneRequest();
            inValue.fromAmount = fromAmount;
            return ((Forex.FortuneMoney_ServiceReference.FortuneMoneySrv)(this)).exchangeFromEuroToKroneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroResponse Forex.FortuneMoney_ServiceReference.FortuneMoneySrv.exchangeFromKroneToEuro(Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroRequest request) {
            return base.Channel.exchangeFromKroneToEuro(request);
        }
        
        public double exchangeFromKroneToEuro(double fromAmount) {
            Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroRequest inValue = new Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroRequest();
            inValue.fromAmount = fromAmount;
            Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroResponse retVal = ((Forex.FortuneMoney_ServiceReference.FortuneMoneySrv)(this)).exchangeFromKroneToEuro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroResponse> Forex.FortuneMoney_ServiceReference.FortuneMoneySrv.exchangeFromKroneToEuroAsync(Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroRequest request) {
            return base.Channel.exchangeFromKroneToEuroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroResponse> exchangeFromKroneToEuroAsync(double fromAmount) {
            Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroRequest inValue = new Forex.FortuneMoney_ServiceReference.exchangeFromKroneToEuroRequest();
            inValue.fromAmount = fromAmount;
            return ((Forex.FortuneMoney_ServiceReference.FortuneMoneySrv)(this)).exchangeFromKroneToEuroAsync(inValue);
        }
    }
}
